### PR TITLE
Make LO finetune optional

### PR DESCRIPTION
**Pull request by howard0su**
LO finetune feature is not ready. Add a button in Debug mode to enable developers playing with it.

### CODE REVIEW

**Comment by howard0su** [comment]
The logic to select LO needs some additional work to polish. The original logic needs SRate information which is not available in RadioHandler today.

**Comment by howard0su** [comment]
@ik1xpv I believe the issue with LO finetune is caused by the r2iq logic. For example, I cannot select 9Mhz as IF, which can perfectly adjust by tunebin.

**Comment by ik1xpv** [comment]
Yes it seems a r2iq logic bug. I'm looking for it but tobay here it is foggy :-)

**Review by ik1xpv — APPROVED** [review]
Looks ok to me

**Comment by ik1xpv** [comment]
The LO Fine Tune optional may help in debugging r2iq. Can we merge it?

**Comment by howard0su** [comment]
sure

**Pull request merged**
