### PR TITLE
try some ideas

### PR DESCRIPTION
**Pull request by howard0su**
I am trying:
1. enable auto vector of C++ compiler
2. Move int16_t -> float into the loop to improve cache usage.
3. optimize dec=0 scenario to avoid using a digit filter.
4. use a[] instead a++, which is preferred based on C++ compiler document on auto vectorize. However it still doesn't work.

### CODE REVIEW

**Comment by howard0su** [comment]
No intention to commit this but like to invite discussions.

**Comment by hayguen** [comment]
> 1. enable auto vector of C++ compiler

we can try this ..

looked up option `/Qpar`: that sounds good

i won't use `/fp:fast` globally. filter design and similar setup calculations should be calculated as exact as possible.
we can check this on specific files .. or (de)activate this per #pragma?

very unsure of this one `/arch:AVX2`:
i would prefer check with `/arch:SSE or max /arch:SSE2`. what is the effective gain with `/arch:AVX2`?
https://en.wikichip.org/wiki/x86/extensions show a cute timeline, when which extension was introduced. AVX2 got introduced 2013. SSE4 sounds good for me - introduced in 2008. 
ExtIO/HDSDR is still 32bit with x86 .. and i'm sure many OMs still use quite old computers!
ideally someone could test RX888 on some older computer?

**Comment by hayguen** [comment]
> 2. Move int16_t -> float into the loop to improve cache usage.

implementation needs some care .. we can try this later on

> 3. optimize dec=0 scenario to avoid using a digit filter.

i still want to test this with a signal generator ..

> 4. use a[] instead a++, which is preferred based on C++ compiler document on auto vectorize. However it still doesn't work.

a[] should be preferred in general, cause it's readability is much better.
we can give this a new try

**Comment by howard0su** [comment]
> 
> 
> > 1. enable auto vector of C++ compiler
> 
> we can try this ..
> 
> looked up option `/Qpar`: that sounds good
> 
> i won't use `/fp:fast` globally. filter design and similar setup calculations should be calculated as exact as possible.
> we can check this on specific files .. or (de)activate this per #pragma?
Let me check. good point.

> 
> very unsure of this one `/arch:AVX2`:
> i would prefer check with `/arch:SSE or max /arch:SSE2`. what is the effective gain with `/arch:AVX2`?
> https://en.wikichip.org/wiki/x86/extensions show a cute timeline, when which extension was introduced. AVX2 got introduced 2013. SSE4 sounds good for me - introduced in 2008.
I think for float32, SSE4 is same as AVX2, length are both 256.

> ExtIO/HDSDR is still 32bit with x86 .. and i'm sure many OMs still use quite old computers!
RX888 needs USB 3.0, which introduced in 2011.

> ideally someone could test RX888 on some older computer?

**Comment by howard0su** [comment]
> 
> 
> > 1. Move int16_t -> float into the loop to improve cache usage.
> 
> implementation needs some care .. we can try this later on
didn't give noticeable perf gain.
> 
> > 1. optimize dec=0 scenario to avoid using a digit filter.
> 
> i still want to test this with a signal generator ..
> 
> > 1. use a[] instead a++, which is preferred based on C++ compiler document on auto vectorize. However it still doesn't work.
> 
> a[] should be preferred in general, cause it's readability is much better.
> we can give this a new try

**Pull request closed without merging**
