### PR TITLE
Support multi channels

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by ik1xpv** [comment]
A run of CMake #207
CMake_207
It looks fine :-)
Very cool architecture! Please continue.
I understand it  partially ;-).  Any idea to test multi channels RX?

**Comment by howard0su** [comment]
we need an application which support mutli channel device.

**Comment by howard0su** [comment]
this change needs polish. I comment out some code around stats and I didn't test UI yet.

**Comment by howard0su** [comment]
also, the algorithm has some memory problem which we didn't notice before. When I added the test cases, it shows up. Check BasicTest2 which shows multi channel and crash.

**Pull request closed without merging**
