### PR TITLE
Avoid memory allocation/free at the critial path

### PR DESCRIPTION
**Pull request by howard0su**
This signficantly reduce USB read latency. And potentially reduce CPU usage as well.

### CODE REVIEW

**Comment by howard0su** [comment]
This will also fix #124

**Comment by hayguen** [comment]
BeginBufferedXfer() in CyAPI.cpp still allocates pXmitBuf:
`PUCHAR pXmitBuf = new UCHAR[iXmitBufSize];`
Should this also get replaced?

By the way:
there are several `ZeroMemory()` calls over the full buffer sizes .. but some lines later, that buffers are `memcpy()`ed anyway ..

**Review by ik1xpv — APPROVED** [review]
It seems to me a better solution.

**Comment by howard0su** [comment]
> Not knowing the Cypress API .. BeginBufferedXfer() in CyAPI.cpp still allocates pXmitBuf:
> `PUCHAR pXmitBuf = new UCHAR[iXmitBufSize];`
> Should this also get replaced?
> 
> By the way:
> there are several `ZeroMemory()` calls over the full buffer sizes .. but some lines later, that buffers are partially `memcpy()`ed anyway ..

We don't use BeginBufferedXfer which stands for buffered transfer. So I didn't bother fixing it. CypressAPI is not well written code from my point of view. I would prefer using CompletionPort to rewrite it to avoid multi threads to queue beginread requests. But not urgent for now as we can use one thread to transfer 128M adc rate data without problem.

**Review by ik1xpv — APPROVED** [review]

**Review by hayguen — APPROVED** [review]

**Pull request merged**
