### PR TITLE
Use blue led for ADC overflow

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by howard0su** [comment]
I did this only for RX888 as I have it to test.

**Review by ik1xpv — CHANGES_REQUESTED** [review]
I have a doubt. I noticed in ADC datasheet:
OFA (Pin 60): Over/Under Flow Digital Output for the A
Bus. OFA is high when an over or under flow has occurred
on the A bus. 
The overflow glitches are 1 ADC clock wide. Please verify if  poolling speed is enough.
I think that an interrupt triggered by OFA maybe another solution ?

**Comment by howard0su** [comment]
then we need a filter to say, in last 1second, there is an overflow.

**Comment by ik1xpv** [comment]
Yes I think so. Maybe we could in far future use the filtered signal to adapt the gain automatically.

**Comment by howard0su** [comment]
Can you help on this?

I think we can use Complex GPIO feature. I find this from TRM:
Table 8-4. Modes Supported by Complex GPIO
>> MEASURE_POS_ONCE
Measure when a signal goes high once and then stop.
Set THRESHOLD=TIMER on posedge.
Set MODE=STATIC.

**Pull request closed without merging**
