### PR TITLE
Cleanup RandioHandler class

### PR DESCRIPTION
**Pull request by howard0su**
Reduce global variables.
Prepare to abstract usb transfer logic out of this class.

### CODE REVIEW

**Comment by howard0su** [comment]
@fventuri I am working on abstract ADCSampling logic out of RadioHandler. SO that we have a different implementation on Linux eventually.

**Review by ik1xpv — APPROVED** [review]
I'm crossing my fingers for solving BUG1001 !

**Comment by fventuri** [comment]
@howard0su - thanks Howard! That will be very useful for having a nice Linux library too.

**Comment by howard0su** [comment]
I saw bug001 several times but the current logic recovered from it.

**Comment by ik1xpv** [comment]
Hi Howard,
that is a good news. Bravo from Italy.
Oscar

**Pull request merged**
