### PR TITLE
Add libusb support and restructure project; pending auto-firmware load

### PR DESCRIPTION
**Pull request by cozycactus**
- Implemented support for libusb in addition to existing cyapi functionality.
- Restructured the file system for enhanced project modularity.
- Note: Automatic firmware loading via USB, as it exists in cyapi, is not yet implemented for libusb. This remains a work in progress.

### CODE REVIEW

**Comment by howard0su** [comment]
please rebase and revalidate.

**Comment by cozycactus** [comment]
> please rebase and revalidate.

what do you mean exactly?

**Comment by howard0su** [comment]
I pushed 2 changes to master. please use 'git rebase' or 'git merge' to merge to this PR so that validation can pass.

**Comment by cozycactus** [comment]
@howard0su done

**Pull request merged**
